apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: logstash
  labels:
    app: logstash
spec:
  ports:
  - port: 5000
    name: logstash-tcp
    targetPort: 5000
    #nodePort: 30930
  type: NodePort
  # clusterIP: None
  # ports:
  # - name: logstash-tcp
  #   port: 5000
  selector:
    app: logstash